### ISSUE TITLE
Remove screenshots from repo tree and add logo to readme

### ISSUE THREAD

**Issue by mogaika** [mogaika/god_of_war_browser#1]

**Comment by mogaika** [comment]
![athn01a](https://user-images.githubusercontent.com/3680954/28489832-6ec6697c-6edd-11e7-8ead-ed37e3870b15.png)
![gow_browser_logo](https://user-images.githubusercontent.com/3680954/28489831-6ec1c660-6edd-11e7-9b08-7c79b20196d8.png)
![sewr01](https://user-images.githubusercontent.com/3680954/28489833-6ecbfc5c-6edd-11e7-9d63-1ca0b060ddec.png)

**Comment by mogaika** [comment]
![gow](https://user-images.githubusercontent.com/3680954/71230603-bd897e00-2303-11ea-8f5e-ef84d81dfef0.gif)

**Comment by mogaika** [comment]
![gow2](https://user-images.githubusercontent.com/3680954/71231581-080cf980-2308-11ea-9dab-5c58b9ad7b4b.gif)

**Comment by HawreUnity** [comment]
Hi, why can't you save the animation?
How can I save animations in FBX format?

**Comment by mogaika** [comment]
@HawreUnity opened new issue for this #3

**Comment by HawreUnity** [comment]
Hi i sent you an email please open it and send me the answer thank you

**Comment by HawreUnity** [comment]
Excuse me so much I had two questions
What is the god_of_war_browser-master tool and how to use it?
How can some sounds be in SBK format to convert them to Wav or MP3  format?

**Comment by leonifc331** [comment]
why is it no longer possible to download the tools: isoreplacer, packer, wadpack and wadunpack? when using gow browser i have an error when i try to replace a kratos texture, (r_hero0)

**Comment by HawreUnity** [comment]
I was able to replace the textures and the sound, but I didn't try it because I was looking for more resources, I was always trying to extract the animation and I was looking forward to the respected creator of this update.
I think it's very simple and it's not that hard to run in the browser and God willing it will succeed soon.

**Comment by mogaika** [comment]
@HawreUnity
> Excuse me so much I had two questions
> What is the god_of_war_browser-master tool and how to use it?

https://github.com/mogaika/god_of_war_browser#instruction
In case you encountered problem write particular issue or question.

> How can some sounds be in SBK format to convert them to Wav or MP3 format?

SBK still not cracked, because format is not that easy. But you can save "Non-SBK" audio banks, like "R_PERM.WAD=>Hero" or "R_SKS.WAD=>sks". Click on audio player using RMB and select "Save audio as..."

@leonifc331
> why is it no longer possible to download the tools: isoreplacer, packer, wadpack and wadunpack? when using gow browser i have an error when i try to replace a kratos texture, (r_hero0)

Because this tools are too old and not recommended to use. Use god of war browser instead, it handles a lot of situations much better and allow to download (![](https://raw.githubusercontent.com/mogaika/god_of_war_browser/1063656ffa5ca7992f31b8738d5e9d2dc7c42f3d/web/data/static/dump-16.png)) or upload (![](https://raw.githubusercontent.com/mogaika/god_of_war_browser/1063656ffa5ca7992f31b8738d5e9d2dc7c42f3d/web/data/static/upload-16.png)) raw information in a lot of places.
In case you really need the tools: install go compiler and write in console
```
go get -d github.com/mogaika/god_of_war_browser/
go build github.com/mogaika/god_of_war_browser/tools/packer # replace packer with any required tool
```
Anyway, it would be better if you create new issue with particular problem you encountered. I just replaced texture "R_HERO0.WAD=>TXR_maiF03" in ps2 iso and it worked.

**Comment by HawreUnity** [comment]
I mean god_of_war_browser-master
Since there are two tools, one god_of_war_browser-master and one god_of_war_browser, these two are no different.
I know how to use god_of_war_browser but I don't know what god_of_war_browser-master is like. I wish you had a video tutorial on the difference between these two and how to execute them.

**Comment by leonifc331** [comment]
I'm sorry, I was not as specific as the error, I can replace the textures, but in particular those of kratos, the first two textures of kratos, if I replace each other gets blurry, and vice versa ... in terms of tools I wanted them to replace the curtscenes of the game (pss)
![image](https://user-images.githubusercontent.com/37820098/71757495-21b85000-2e75-11ea-84a8-bf38c7d2086e.png)

**Comment by mogaika** [comment]
@leonifc331 
opened new issue for this problem #5

@HawreUnity
master - is just a git branch name. it means latest version of repository.
> Do you think you can extract the animations?

yes, but I need more time. And probably I will use collada format, since it's easier that fbx

> Does it take too long to get the new update?

do not know

> I sent you a series of suggestions on how to work with this tool, did you look?

yes, maybe I will implement some of them in future. Currently focus on functionality, instead of ui/ux experience

**Comment by HawreUnity** [comment]
Thank you very much Master, I am looking forward to the new update of this tool and thank you very much for giving us this tool for free

**Comment by HawreUnity** [comment]
Hello again, dear master, in order to bother you, I wanted to know, are you not working on this program anymore? I have been waiting for a new update of your program for more than a year and a half, so that you can pull out the animations in FBX format, or you can do the models with the ability to extract the mesh in a straightforward way, because at the moment it only reads vortices and Makes the model fragmented, thank you for answering
