### ISSUE TITLE
FBX mesh/ animation

### ISSUE THREAD

**Issue by leonifc331** [mogaika/god_of_war_browser#10]
still not possible to import the fbx files that the tool allows us to download?
![image](https://user-images.githubusercontent.com/37820098/77243006-95036f80-6be3-11ea-96fd-f2155cedd6c6.png)

**Comment by mogaika** [comment]
Fbx exporter still in progress. You can use "Open Asset Import Library: Viewer" (part of assimp project) to open produced fbx files and convert them to any other format

**Comment by aniszeus** [comment]
I can't for it man good luck

**Comment by mogaika** [comment]
Understood. I currently have no that much time to add such big features, if you still will be interested come back somewhere early summer

**Comment by mogaika** [comment]
Closed as duplicate of #3
