### ISSUE TITLE
God of war 2 iso access problem 

### ISSUE THREAD

**Issue by vigneshvampire** [mogaika/god_of_war_browser#14]
ok thanks for the response now i use god of war browser with ISO like this format 

god_of_war_browser.exe -iso "D:\New folder (3)\god_of_war_browser.1.125\GOW2.iso" -gowversion 2 -ps ps3 

But i can access only 3d model *not texture and any other files..incase i change or swap 3d model only that iso freeze while running via pcsx2 ...

i want access all files and repack it like gow 1 it's very easy smooth process ...

Please fix god of war 2 access,repack,save problem .... and i am waiting for gow.psarc repack also

thank you so much for your tool, it's very useful for me ..hope soon you fix it

**Comment by mogaika** [comment]
Try to change ps3 to ps2 in your command line.

But overall tool working much better on gow1 than gow2 because they changed some stuff in it and I mostly focus on gow1.

**Comment by vigneshvampire** [comment]
> 
> 
> Try to change ps3 to ps2 in your command line.
> 
> But overall tool working much better on gow1 than gow2 because they changed some stuff in it and I mostly focus on gow1.

thank you so much it's working fine,now i forget single line cmd ps3 now i change it ps2 now i can access everything it's working fine ...

**Comment by mogaika** [comment]
Glad to hear
