### ISSUE TITLE
I just want to know this technique they used to make Ares fire texture looks like this 

### ISSUE THREAD

**Issue by aniszeus** [mogaika/god_of_war_browser#38]
![ares technique](https://user-images.githubusercontent.com/57457822/106261527-f8a5f280-6221-11eb-82cd-6fdb3b053cbe.jpg)
![ares technique2](https://user-images.githubusercontent.com/57457822/106261570-03608780-6222-11eb-95a5-a62c1fa9e1a0.jpg)

**Comment by mogaika** [comment]
Usual mesh:
![image](https://user-images.githubusercontent.com/3680954/106262477-2300ab80-6234-11eb-8d12-b39ea7dbbc67.png)

Mesh with material that has such options:
"DisableDepthWrite": true, (a common option when you need to render additive mesh)
"RenderingAdditive": true, (additive rendering usually used for particles, all additive objects rendered after usual ones)
Material UV animated to be scrolled in one direction
![image](https://user-images.githubusercontent.com/3680954/106262956-cc47a180-6234-11eb-88cd-c99454c54036.png)

Also, there is an animation of material color, but it's not parsed and not showed in gow browser
![image](https://user-images.githubusercontent.com/3680954/106262502-2dbb4080-6234-11eb-8365-d5ce75616f53.png)

**Comment by aniszeus** [comment]
Thanks for the information
