### ISSUE TITLE
Texture replacer incorrectly handle situations when same palette used in different textures

### ISSUE THREAD

**Issue by mogaika** [mogaika/god_of_war_browser#5]
I'm sorry, I was not as specific as the error, I can replace the textures, but in particular those of kratos, the first two textures of kratos, if I replace each other gets blurry, and vice versa ... in terms of tools I wanted them to replace the curtscenes of the game (pss)
![image](https://user-images.githubusercontent.com/37820098/71757495-21b85000-2e75-11ea-84a8-bf38c7d2086e.png)

_Originally posted by @leonifc331 in https://github.com/mogaika/god_of_war_browser/issues/1#issuecomment-570742735_

Problem in these two particular textures TXR_maiF02 and TXR_maiF01. They both use same palette PAL_MAI01F, so when you change one the texture, you breaks palette for other one texture. gow-browser currently can't handle such situations.
I can add "Add own pallete" checkbox for this specific cases.
Or we can detect automatically if palette used by multiply textures and create own palette in such cases.
In any case functionality which adds new information to wad files can break game, because every wad file have heap size limitation. And if unpacked (by game engine) wad file will be over this heap size game will crash.

**Comment by mogaika** [comment]
@leonifc331 download new version and when replacing one of the TXR_maiF0* textures, try to use new "Create new palette for replaced texture" checkbox. With this checkbox gow-browser will create new PAL_MAI01F resource specifically for texture you replacing. This should solve palette conflict. Be aware that you do not need to use this checkbox after you used it once. On screenshot below PAL_MAI01F0 - newly created palette.
![image](https://user-images.githubusercontent.com/3680954/71759556-3d991180-2ec8-11ea-89da-25eee9f63e8f.png)

**Comment by leonifc331** [comment]
amazing, you seem to have made it work :o 
but for me here did not appear this new check box :(
![image](https://user-images.githubusercontent.com/37820098/71760743-28f55300-2ea1-11ea-846b-ef61b26e0e36.png)

**Comment by mogaika** [comment]
> 
> 
> amazing, you seem to have made it work :o
> but for me here did not appear this new check box :(
> ![image](https://user-images.githubusercontent.com/37820098/71760743-28f55300-2ea1-11ea-846b-ef61b26e0e36.png)

Oh, forgot to merge pull request #6
Please check again

**Comment by leonifc331** [comment]
thank you so much, its work!
![image](https://user-images.githubusercontent.com/37820098/71766987-1d2b8000-2ee5-11ea-9ea2-f7f9ca1c738a.png)
