### ISSUE TITLE
where is the texture or files name the "Red" Omega Logo at God of War 1 or 2??

### ISSUE THREAD

**Issue by Angoks** [mogaika/god_of_war_browser#56]
![Screenshot (429)](https://user-images.githubusercontent.com/65075830/116496002-07fb1180-a8df-11eb-875d-219f77282412.png)

**Comment by mogaika** [comment]
There is no texture for it. It's a colored mesh.

**Comment by Angoks** [comment]
> There is no texture for it. It's a colored mesh.

oh so it's not possible to changed the color? i want change color from Red to Blue
