### ISSUE TITLE
No way to download latest build/no discord link

### ISSUE THREAD

**Issue by snowboundmage2** [mogaika/god_of_war_browser#60]
appveyor deletes any artifacts over a month old, and the latest build was 2 months ago, where to get latest build?

also, the discord link is dead

**Comment by xDShot** [comment]
go build

**Comment by mogaika** [comment]
Rebuilded artifacts for now. Sad, they used to have 6 months and AFAIR it was unlimited for master branches

**Comment by snowboundmage2** [comment]
thank you
