### ISSUE TITLE
i can't acess ps3 wads like ps2 wads

### ISSUE THREAD

**Issue by vigneshvampire** [mogaika/god_of_war_browser#7]
god_of_war_browser.exe  -psarc "C:\Users\vampire\Desktop\Ps3 gow tool\GOW1\PART1.psarc" -ps ps3 gowversion 1

i can access only wad files download and upload option,not click and view inside files(PS3.psarc) option like ps2 .pak files...

and i try to acess WAD files it's show

Starting web server on address ':8000'
.wad
Error getting directory 'C:\Users\vampire\Desktop\Ps3 gow tool\GOW1\wad_arena06.wad_ps3' info: Readdir C:\Users\vampire\Desktop\Ps3 gow tool\GOW1\wad_arena06.wad_ps3: The system cannot find the path specified.

**Comment by mogaika** [comment]
Thanks for report!
I use this command line and everything works perfectly.
`-psarc "BCES00791\PS3_GAME\USRDIR\GOW1\exec\gow1.psarc"  -gowversion 1 -ps ps3`

Looks like you missed minus before gowversion parameter.
If this is not the case, please provide console output. You can find them in `applogs` directory

**Comment by vigneshvampire** [comment]
> -psarc "BCES00791\PS3_GAME\USRDIR\GOW1\exec\gow1.psarc" -gowversion 1 -ps ps3

it's working think you,if it possible to open god of war 3 psarc files...??

**Comment by mogaika** [comment]
@vigneshvampire sorry, missed your response. Problem is that ps3 textures have a different format.
I added experimental support of them in development branch, you can [download it there](https://ci.appveyor.com/project/mogaika/god-of-war-browser/branch/dev/artifacts).

ps3 version has every texture in 2x size, and looks like even not upscaled, but based on original artists versions.

**Comment by vigneshvampire** [comment]
thank now i can access gow ps3 textures but i can't replace texture or 3d models like ps2 gow pak,i got this error msg 

127.0.0.1:8000 says Error replacing: change texture error. Do not support gfic with DatasCount != 1

**Comment by mogaika** [comment]
> 
> 
> thank now i can access gow ps3 textures but i can't replace texture or 3d models like ps2 gow pak,i got this error msg
> 
> 127.0.0.1:8000 says Error replacing: change texture error. Do not support gfic with DatasCount != 1
Yeah, I didn't made converter for ps3 textures, yet. Wait for update this week, it's simple to make it

**Comment by mogaika** [comment]
okay, turned out that I didn't implemented psarc packer yet also, so ps3 texture changer delays in time
