### ISSUE TITLE
Lable "OFF/ON" Vibration func. How can i modified this string?

### ISSUE THREAD

**Issue by YAGAMI55** [mogaika/god_of_war_browser#8]
So, i started tranlating first GoW PS2 version to russian lang. You tool is amazing. Respect to you))) But i cant (maybe i something mised up) change lables string in Vibrations in option, String "OFF/ON" its a meshpart with gliph, but i cant change them.
How i can change them?
Sorry for my bad english.

**Comment by mogaika** [comment]
Спасибо )

В "Labels editor" находишь строку с "Vibration", тыкаешь на его id. Попадаешь на "Static label" объект. Переходишь на его parent. Там будут элементы и их анимации. Находишь нужный элемент, в данном случае он называется "VibrationOnOff", но он оказывается "Dynamic label", а не static, значит меняется через скрипты. Поднимаемся на еще одного родителя выше (Data7[233] в моем случае), в скрипте 5 под названием "Options" видим упоминание "PauseVibration" (это поле можно было видеть в параметрах Dynamic label) и что рядом упоминаются строки On/Off.

В общем эти строки находятся в скриптах, и раньше их можно было менять их через вкладку "Scripts strings", однако после того как унифицировал некоторые вещи для поддержки psvita/ps3 (т.к. у них отличия в хранении скриптовых строк), сломалась эта вкладка. Можешь использовать старую версию, ВРОДЕ, последний коммит что умеет менять эти строки 11e3b8178405beb319b05d44a0f778f8f2b621aa. Вот [ссылка на архив](https://github.com/mogaika/god_of_war_browser/archive/11e3b8178405beb319b05d44a0f778f8f2b621aa.zip). Для компиляции надо установить golang и выполнить внутри папки с go файлами:
```sh
go mod init github.com/mogaika/god_of_war_browser
go build .
```
Не забудь сделать бекап перед изменением, т.к. старая версия, мало ли что там не работает. Можно делать бекапы отдельных wad файлов используя кнопки в списке слева.

Еще хочу сказать что перевод игры на ps vita https://vk.com/wall-170723719_2012 уже делали, может смогут тебе помочь субтитрами или еще чем.

**Comment by YAGAMI55** [comment]
Вау, свой человек)
Спасибо за тулзу, если бы не она, мучался бы с расшифровкой. Кстати скомпилировал на основе твоих исходников packer(для pak файлов), но он для PS2 версии не годен, т.к там строго по LBA файлы идут. Спасибо за архив, я так и понял что Script String ковырнуть надо, а тут не пошло дело. Опробую)
По поводу порта для Vita знаком, вот и решил с нуля перевести версию PS2, у неё нет норм ни текста, ни звука
Если интересно)))
https://vk.com/club192124267
Выкладываю скрины и звуки по переводу)
Спасибо за помощь!
